### ISSUE TITLE
Suggestion in documentation enhancement

### ISSUE THREAD

**Issue by CSyl** [ecmwf/anemoi-graphs#57]
### What maintenance does this project need?

Suggestions for doc. enhancements:

1. Under https://anemoi-graphs.readthedocs.io/en/latest/usage/getting_started.html, the KNN method of build edges' argument of defining the number of nearest neighbors has been updated on both develop branch & main branch. Suggestion is to update the argument defining the number of nearest neighbors in the anemoi-graphs latest documentation from "nearest_neighbours" to "num_nearest_neighbours"

2. Under https://anemoi-graphs.readthedocs.io/en/latest/graphs/node_attributes/weights.html, the "anemoi.graphs.nodes.nodes.ZarrDatasetNodeBuilder" & "anemoi.graphs.nodes.weights.Area" do not exist within the develop branch (weights.py does not exist) nor within the main branch of the source code (has weights.py, but the method is renamed to AreaWeights) so, the suggesting that the config. file shown in guide will need updates regarding those parameters.

**Comment by JPXKQX** [comment]
Thank you for raising these errors. They should be fixed with the [next documentation release](https://github.com/ecmwf/anemoi-graphs/pull/42) [[docs](https://anemoi-graphs--42.org.readthedocs.build/en/42/index.html)].
